### ISSUE TITLE
Cloud cover

### ISSUE THREAD

**Issue by smpenna3** [z0glen/cloud-tracker#5]
Does the weather API you use show the percent cloud cover? Would be nice to see that too if possible.

**Comment by z0glen** [comment]
addressed in commit 3d13ec974921b4ee6ff8edb42b5983ed2291a8ea, waiting to verify with tomorrow's email

**Comment by smpenna3** [comment]
Their API seems pretty nice

**Comment by z0glen** [comment]
Yeah it gives quite a bit of information. Functionality verified by test email.
